name: eventhub
description: EventHub mobile app (MVP)
version: 0.1.0+1 

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  http: ^1.2.2
  shared_preferences: ^2.3.2
  go_router: ^14.2.0
  intl: ^0.19.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  image_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true 
