name: vibe
description: Vibe mobile app (MVP)
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  shared_preferences: ^2.3.2
  firebase_core: ^3.5.0
  firebase_messaging: ^15.1.0
  flutter_app_badger: ^1.5.0
  go_router: ^14.2.0
  intl: ^0.19.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  image_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  image: ^4.1.3
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/vibe_icon.png"
  adaptive_icon_background: "#0F0724"
  adaptive_icon_foreground: "assets/icons/vibe_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
flutter:
  uses-material-design: true
